### ISSUE TITLE
Getting string indices must be integers error when running snapshot 

### ISSUE THREAD

**Issue by ddl-ymaachi** [dominodatalab/domino-maintenance-mode#6]
When running the dmm snapshot for some customers we had this error: 
```bash
domino_support@domino-deploy:/domino/deployment$ docker run -v /home/domino_support/dmm:/export  -e DOMINO_API_KEY=xxxxxxxxxxx -e DOMINO_HOSTNAME=https://domino-hostname.com/ -e DOMINO_SSL_NO_VERIFY=true --rm  quay.io/domino/dmm snapshot domino-dmm-snapshot.json
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'domino-hostname.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
INFO:domino_maintenance_mode.projects:Found 2 projects.
Traceback (most recent call last):
  File "/usr/local/bin/dmm", line 33, in <module>
    sys.exit(load_entry_point('domino-maintenance-mode', 'console_scripts', 'dmm')())
  File "/app/domino_maintenance_mode/cli.py", line 199, in main
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/domino_maintenance_mode/cli.py", line 56, in snapshot
    projects = fetch_projects()
  File "/app/domino_maintenance_mode/projects.py", line 36, in fetch_projects
    return list(
  File "/app/domino_maintenance_mode/projects.py", line 39, in <lambda>
    project["id"], project["name"], project["ownerUsername"]
TypeError: string indices must be integers

```
Maybe related to some unallowed characters in `project["id"], project["name"], project["ownerUsername"]`

**Comment by ddl-m-coaker** [comment]
Moved to Jira ([DOM-43622](https://dominodatalab.atlassian.net/browse/DOM-43622))
